In [1]:
import numpy as np

In [2]:
pos = np.array([[2, 1], [9, 12], [11, -3]])
print(np.linalg.norm(pos,axis = 1)**2)
print(pos)

[  5. 225. 130.]
[[ 2  1]
 [ 9 12]
 [11 -3]]


In [4]:
mask = pos[:,0] > 5
print(pos)
pos[mask,0] += 1
print(pos)

[[ 2  1]
 [10 13]
 [12 -2]]
[[ 2  1]
 [11 13]
 [13 -2]]
